---
title: R Cheats
author: Annotations and code snippets in R
output: 
  html_document:
    theme: readable
    css: custom.css
    includes:
      after_body: footer.html
---

<style>
  body{
    font-size: 16px;
    line-height: 24px;
  }
  .main-container {
    max-width: 1200px;
  }
</style>

## Description
My personal annotations and code snippets in R. It's a material to use as
reference when coding in R.

In conjunction with public cheat-sheets, is a good helper to avoid memorize
everything.

## Index
- [Efficient R code](efficient-R-code.html): my personal annotations taken from
Datacamp's course;
- [Introduction to writing functions in R](intro-to-wrinting-functions-in-r.html)
:my personal annotations taken from Datacamp's course;
- [R programming](r-programming.html): notes and code snippets about R
programming language itself, not about statistics or data manipulation (work in
progress).
- [Statistics in R](statistics-in-R.html): a reference about statistics in
R (work in progress);
- [Tidy data](tidy-data.html): useful code snippets to tidy data up (work in
progress).
- [Web data in R](web-data-in-R.html): my personal annotations taken from
Datacamp's course.