---
title: Statistics in R
author: My personal knowledge base
output: 
  html_document:
    theme: readable
    css: custom.css
    includes:
      after_body: footer.html
---

<style>
body{
  font-size: 16px;
  line-height: 24px;
}
.main-container {
  max-width: 1200px;
}
</style>

###### [Back to home](index.html)

### Contents
[Linear models](#linear-models)  
[Quantiles](#quantiles)

### Linear models {#linear-models}
Basic prediction from a linear model:

```{r}
suppressPackageStartupMessages(library(dplyr))

snake_river_visits <- readRDS('data/snake_river_visits.rds')
str(snake_river_visits)
snake_river_explanatory <- readRDS('data/snake_river_explanatory.rds')
str(snake_river_explanatory)

model <- lm(n_visits ~ gender + income + travel, snake_river_visits)

snake_river_explanatory %>%
  mutate(predicted_n_visits = predict(model, .))%>%
  arrange(desc(predicted_n_visits))
```

### Quantiles {#quantiles}
A custom function ```cut_by_quantile()``` that converts a numeric vector into a categorical variable where quantiles define the cut points:

```{r}
cut_by_quantile <- function(x, n = 5, na.rm = FALSE, labels = NULL, 
                            interval_type = c("(lo, hi]", "[lo, hi)")) {
  interval_type <- match.arg(interval_type)
  probs <- seq(0, 1, length.out = n + 1)
  qtiles <- quantile(x, probs, na.rm = na.rm, names = FALSE)
  right <- switch(interval_type, "(lo, hi]" = TRUE, "[lo, hi)" = FALSE)
  cut(x, qtiles, labels = labels, right = right, include.lowest = TRUE)
}

# Remove the interval_type argument from the call
cut_by_quantile(snake_river_visits$n_visits)
```

